import type { Metadata } from "next"
import { Playfair_Display, Inter, Poppins } from "next/font/google"
import "./globals.css"

export const inter = Inter({
  subsets: ["latin"]
})

export const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
})

export const poppins = Poppins({
  weight: ['400'],
  subsets: ["latin"],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
